export enum Country {
    AF = "AF",
    AL = "AL",
    DZ = "DZ",
    AS = "AS",
    AD = "AD",
    AO = "AO",
    AI = "AI",
    AQ = "AQ",
    AG = "AG",
    AR = "AR",
    AM = "AM",
    AW = "AW",
    AU = "AU",
    AT = "AT",
    AZ = "AZ",

    BS = "BS",
    BH = "BH",
    BD = "BD",
    BB = "BB",
    BY = "BY",
    BE = "BE",
    BZ = "BZ",
    BJ = "BJ",
    BM = "BM",
    BT = "BT",
    BO = "BO",
    BA = "BA",
    BW = "BW",
    BR = "BR",
    BN = "BN",
    BG = "BG",
    BF = "BF",
    BI = "BI",

    KH = "KH",
    CM = "CM",
    CA = "CA",
    CV = "CV",
    KY = "KY",
    CF = "CF",
    TD = "TD",
    CL = "CL",
    CN = "CN",
    CO = "CO",
    KM = "KM",
    CG = "CG",
    CD = "CD",
    CR = "CR",
    CI = "CI",
    HR = "HR",
    CU = "CU",
    CY = "CY",
    CZ = "CZ",

    DK = "DK",
    DJ = "DJ",
    DM = "DM",
    DO = "DO",

    EC = "EC",
    EG = "EG",
    SV = "SV",
    GQ = "GQ",
    ER = "ER",
    EE = "EE",
    SZ = "SZ",
    ET = "ET",

    FI = "FI",
    FJ = "FJ",
    FR = "FR",

    GA = "GA",
    GM = "GM",
    GE = "GE",
    DE = "DE",
    GH = "GH",
    GR = "GR",
    GD = "GD",
    GT = "GT",
    GN = "GN",
    GW = "GW",
    GY = "GY",

    HT = "HT",
    HN = "HN",
    HU = "HU",

    IS = "IS",
    IN = "IN",
    ID = "ID",
    IR = "IR",
    IQ = "IQ",
    IE = "IE",
    IL = "IL",
    IT = "IT",

    JM = "JM",
    JP = "JP",
    JO = "JO",

    KZ = "KZ",
    KE = "KE",
    KI = "KI",
    KP = "KP",
    KR = "KR",
    KW = "KW",
    KG = "KG",

    LA = "LA",
    LV = "LV",
    LB = "LB",
    LS = "LS",
    LR = "LR",
    LY = "LY",
    LI = "LI",
    LT = "LT",
    LU = "LU",

    MG = "MG",
    MW = "MW",
    MY = "MY",
    MV = "MV",
    ML = "ML",
    MT = "MT",
    MH = "MH",
    MR = "MR",
    MU = "MU",
    MX = "MX",
    FM = "FM",
    MD = "MD",
    MC = "MC",
    MN = "MN",
    ME = "ME",
    MA = "MA",
    MZ = "MZ",
    MM = "MM",

    NA = "NA",
    NR = "NR",
    NP = "NP",
    NL = "NL",
    NZ = "NZ",
    NI = "NI",
    NE = "NE",
    NG = "NG",
    NO = "NO",

    OM = "OM",

    PK = "PK",
    PW = "PW",
    PA = "PA",
    PG = "PG",
    PY = "PY",
    PE = "PE",
    PH = "PH",
    PL = "PL",
    PT = "PT",

    QA = "QA",

    RO = "RO",
    RU = "RU",
    RW = "RW",

    KN = "KN",
    LC = "LC",
    VC = "VC",
    WS = "WS",
    SM = "SM",
    ST = "ST",
    SA = "SA",
    SN = "SN",
    RS = "RS",
    SC = "SC",
    SL = "SL",
    SG = "SG",
    SK = "SK",
    SI = "SI",
    SB = "SB",
    SO = "SO",
    ZA = "ZA",
    ES = "ES",
    LK = "LK",
    SD = "SD",
    SR = "SR",
    SE = "SE",
    CH = "CH",
    SY = "SY",

    TW = "TW",
    TJ = "TJ",
    TZ = "TZ",
    TH = "TH",
    TL = "TL",
    TG = "TG",
    TO = "TO",
    TT = "TT",
    TN = "TN",
    TR = "TR",
    TM = "TM",
    TV = "TV",

    UG = "UG",
    UA = "UA",
    AE = "AE",
    UK = "UK",
    GB = "GB",
    US = "US",
    UY = "UY",
    UZ = "UZ",

    VU = "VU",
    VA = "VA",
    VE = "VE",
    VN = "VN",

    YE = "YE",
    ZM = "ZM",
    ZW = "ZW"
}


/**
 * 
 * @param country the country code
 * @param language the language of the country name, by default DE
 * @returns the name of the country in the specified language
 */
export function getCountryName(country: Country, language = "DE"): string {
    return translations[country]?.[language] || country;
}

/**
 * 
 * @returns the country codes
 */
export function getAllCountryCodes(): Country[] {
    return Object.values(Country);
}

/**
 * 
 * @param language the language of the country names, by default DE
 * @returns all countries with their codes and names in the specified language
 */
export function getAllCountriesWithNames(language = "DE"): { code: Country, name: string }[] {
    return Object.values(Country).map(code => ({
        code,
        name: getCountryName(code, language.toUpperCase())
    }));
}

const translations: Record<Country, Record<string, string>> = {
    [Country.AF]: { DE: "Afghanistan" },
    [Country.AL]: { DE: "Albanien" },
    [Country.DZ]: { DE: "Algerien" },
    [Country.AS]: { DE: "Amerikanisch-Samoa" },
    [Country.AD]: { DE: "Andorra" },
    [Country.AO]: { DE: "Angola" },
    [Country.AI]: { DE: "Anguilla" },
    [Country.AQ]: { DE: "Antarktis" },
    [Country.AG]: { DE: "Antigua und Barbuda" },
    [Country.AR]: { DE: "Argentinien" },
    [Country.AM]: { DE: "Armenien" },
    [Country.AW]: { DE: "Aruba" },
    [Country.AU]: { DE: "Australien" },
    [Country.AT]: { DE: "Österreich" },
    [Country.AZ]: { DE: "Aserbaidschan" },

    [Country.BS]: { DE: "Bahamas" },
    [Country.BH]: { DE: "Bahrain" },
    [Country.BD]: { DE: "Bangladesch" },
    [Country.BB]: { DE: "Barbados" },
    [Country.BY]: { DE: "Belarus" },
    [Country.BE]: { DE: "Belgien" },
    [Country.BZ]: { DE: "Belize" },
    [Country.BJ]: { DE: "Benin" },
    [Country.BM]: { DE: "Bermuda" },
    [Country.BT]: { DE: "Bhutan" },
    [Country.BO]: { DE: "Bolivien" },
    [Country.BA]: { DE: "Bosnien und Herzegowina" },
    [Country.BW]: { DE: "Botswana" },
    [Country.BR]: { DE: "Brasilien" },
    [Country.BN]: { DE: "Brunei" },
    [Country.BG]: { DE: "Bulgarien" },
    [Country.BF]: { DE: "Burkina Faso" },
    [Country.BI]: { DE: "Burundi" },

    [Country.KH]: { DE: "Kambodscha" },
    [Country.CM]: { DE: "Kamerun" },
    [Country.CA]: { DE: "Kanada" },
    [Country.CV]: { DE: "Kap Verde" },
    [Country.KY]: { DE: "Kaimaninseln" },
    [Country.CF]: { DE: "Zentralafrikanische Republik" },
    [Country.TD]: { DE: "Tschad" },
    [Country.CL]: { DE: "Chile" },
    [Country.CN]: { DE: "China" },
    [Country.CO]: { DE: "Kolumbien" },
    [Country.KM]: { DE: "Komoren" },
    [Country.CG]: { DE: "Republik Kongo" },
    [Country.CD]: { DE: "Demokratische Republik Kongo" },
    [Country.CR]: { DE: "Costa Rica" },
    [Country.CI]: { DE: "Elfenbeinküste" },
    [Country.HR]: { DE: "Kroatien" },
    [Country.CU]: { DE: "Kuba" },
    [Country.CY]: { DE: "Zypern" },
    [Country.CZ]: { DE: "Tschechien" },

    [Country.DK]: { DE: "Dänemark" },
    [Country.DJ]: { DE: "Dschibuti" },
    [Country.DM]: { DE: "Dominica" },
    [Country.DO]: { DE: "Dominikanische Republik" },

    [Country.EC]: { DE: "Ecuador" },
    [Country.EG]: { DE: "Ägypten" },
    [Country.SV]: { DE: "El Salvador" },
    [Country.GQ]: { DE: "Äquatorialguinea" },
    [Country.ER]: { DE: "Eritrea" },
    [Country.EE]: { DE: "Estland" },
    [Country.SZ]: { DE: "Eswatini" },
    [Country.ET]: { DE: "Äthiopien" },

    [Country.FI]: { DE: "Finnland" },
    [Country.FJ]: { DE: "Fidschi" },
    [Country.FR]: { DE: "Frankreich" },

    [Country.GA]: { DE: "Gabun" },
    [Country.GM]: { DE: "Gambia" },
    [Country.GE]: { DE: "Georgien" },
    [Country.DE]: { DE: "Deutschland" },
    [Country.GH]: { DE: "Ghana" },
    [Country.GR]: { DE: "Griechenland" },
    [Country.GD]: { DE: "Grenada" },
    [Country.GT]: { DE: "Guatemala" },
    [Country.GN]: { DE: "Guinea" },
    [Country.GW]: { DE: "Guinea-Bissau" },
    [Country.GY]: { DE: "Guyana" },

    [Country.HT]: { DE: "Haiti" },
    [Country.HN]: { DE: "Honduras" },
    [Country.HU]: { DE: "Ungarn" },

    [Country.IS]: { DE: "Island" },
    [Country.IN]: { DE: "Indien" },
    [Country.ID]: { DE: "Indonesien" },
    [Country.IR]: { DE: "Iran" },
    [Country.IQ]: { DE: "Irak" },
    [Country.IE]: { DE: "Irland" },
    [Country.IL]: { DE: "Israel" },
    [Country.IT]: { DE: "Italien" },

    [Country.JM]: { DE: "Jamaika" },
    [Country.JP]: { DE: "Japan" },
    [Country.JO]: { DE: "Jordanien" },

    [Country.KZ]: { DE: "Kasachstan" },
    [Country.KE]: { DE: "Kenia" },
    [Country.KI]: { DE: "Kiribati" },
    [Country.KP]: { DE: "Nordkorea" },
    [Country.KR]: { DE: "Südkorea" },
    [Country.KW]: { DE: "Kuwait" },
    [Country.KG]: { DE: "Kirgisistan" },

    [Country.LA]: { DE: "Laos" },
    [Country.LV]: { DE: "Lettland" },
    [Country.LB]: { DE: "Libanon" },
    [Country.LS]: { DE: "Lesotho" },
    [Country.LR]: { DE: "Liberia" },
    [Country.LY]: { DE: "Libyen" },
    [Country.LI]: { DE: "Liechtenstein" },
    [Country.LT]: { DE: "Litauen" },
    [Country.LU]: { DE: "Luxemburg" },

    [Country.MX]: { DE: "Mexiko" },
    [Country.MD]: { DE: "Moldau" },
    [Country.MC]: { DE: "Monaco" },
    [Country.MN]: { DE: "Mongolei" },
    [Country.ME]: { DE: "Montenegro" },
    [Country.MA]: { DE: "Marokko" },
    [Country.MZ]: { DE: "Mosambik" },
    [Country.MM]: { DE: "Myanmar" },

    [Country.NL]: { DE: "Niederlande" },
    [Country.NO]: { DE: "Norwegen" },
    [Country.PL]: { DE: "Polen" },
    [Country.PT]: { DE: "Portugal" },

    [Country.RO]: { DE: "Rumänien" },
    [Country.RU]: { DE: "Russland" },

    [Country.SE]: { DE: "Schweden" },
    [Country.CH]: { DE: "Schweiz" },
    [Country.ES]: { DE: "Spanien" },

    [Country.TR]: { DE: "Türkei" },

    [Country.UA]: { DE: "Ukraine" },
    [Country.AE]: { DE: "Vereinigte Arabische Emirate" },
    [Country.UK]: { DE: "Vereinigtes Königreich" },
    [Country.GB]: { DE: "Vereinigtes Königreich" },
    [Country.US]: { DE: "Vereinigte Staaten" },

    [Country.VN]: { DE: "Vietnam" },

    [Country.ZA]: { DE: "Südafrika" },
    [Country.MG]: { DE: "Madagaskar" },
    [Country.MW]: { DE: "Malawi" },
    [Country.MY]: { DE: "Malaysia" },
    [Country.MV]: { DE: "Malediven" },
    [Country.ML]: { DE: "Mali" },
    [Country.MT]: { DE: "Malta" },
    [Country.MH]: { DE: "Marshallinseln" },
    [Country.MR]: { DE: "Mauretanien" },
    [Country.MU]: { DE: "Mauritius" },
    [Country.FM]: { DE: "Mikronesien" },

    [Country.NA]: { DE: "Namibia" },
    [Country.NR]: { DE: "Nauru" },
    [Country.NP]: { DE: "Nepal" },
    [Country.NZ]: { DE: "Neuseeland" },
    [Country.NI]: { DE: "Nicaragua" },
    [Country.NE]: { DE: "Niger" },
    [Country.NG]: { DE: "Nigeria" },

    [Country.OM]: { DE: "Oman" },

    [Country.PK]: { DE: "Pakistan" },
    [Country.PW]: { DE: "Palau" },
    [Country.PA]: { DE: "Panama" },
    [Country.PG]: { DE: "Papua-Neuguinea" },
    [Country.PY]: { DE: "Paraguay" },
    [Country.PE]: { DE: "Peru" },
    [Country.PH]: { DE: "Philippinen" },

    [Country.QA]: { DE: "Katar" },

    [Country.RW]: { DE: "Ruanda" },

    [Country.KN]: { DE: "St. Kitts und Nevis" },
    [Country.LC]: { DE: "St. Lucia" },
    [Country.VC]: { DE: "St. Vincent und die Grenadinen" },

    [Country.WS]: { DE: "Samoa" },
    [Country.SM]: { DE: "San Marino" },
    [Country.ST]: { DE: "São Tomé und Príncipe" },
    [Country.SA]: { DE: "Saudi-Arabien" },
    [Country.SN]: { DE: "Senegal" },
    [Country.RS]: { DE: "Serbien" },
    [Country.SC]: { DE: "Seychellen" },
    [Country.SL]: { DE: "Sierra Leone" },
    [Country.SG]: { DE: "Singapur" },
    [Country.SK]: { DE: "Slowakei" },
    [Country.SI]: { DE: "Slowenien" },
    [Country.SB]: { DE: "Salomonen" },
    [Country.SO]: { DE: "Somalia" },

    [Country.LK]: { DE: "Sri Lanka" },
    [Country.SD]: { DE: "Sudan" },
    [Country.SR]: { DE: "Suriname" },
    [Country.SY]: { DE: "Syrien" },

    [Country.TW]: { DE: "Taiwan" },
    [Country.TJ]: { DE: "Tadschikistan" },
    [Country.TZ]: { DE: "Tansania" },
    [Country.TH]: { DE: "Thailand" },
    [Country.TL]: { DE: "Timor-Leste" },
    [Country.TG]: { DE: "Togo" },
    [Country.TO]: { DE: "Tonga" },
    [Country.TT]: { DE: "Trinidad und Tobago" },
    [Country.TN]: { DE: "Tunesien" },
    [Country.TM]: { DE: "Turkmenistan" },
    [Country.TV]: { DE: "Tuvalu" },

    [Country.UG]: { DE: "Uganda" },
    [Country.UY]: { DE: "Uruguay" },
    [Country.UZ]: { DE: "Usbekistan" },

    [Country.VU]: { DE: "Vanuatu" },
    [Country.VA]: { DE: "Vatikanstadt" },
    [Country.VE]: { DE: "Venezuela" },

    [Country.YE]: { DE: "Jemen" },

    [Country.ZM]: { DE: "Sambia" },
    [Country.ZW]: { DE: "Simbabwe" },
}